export const GET_TIMETABLE = "GET_TIMETABLE";
export const GET_ONE_TIMETABLE = "GET_ONE_TIMETABLE";
export const ADD_TIMETABLE = "ADD_TIMETABLE";
export const UPDATE_TIMETABLE = "UPDATE_TIMETABLE";
export const DELETE_TIMETABLE = "DELETE_TIMETABLE";
