export const GET_MOVIE = 'GET_MOVIE'
export const GET_ONE_MOVIE = 'GET_ONE_MOVIE'
export const ADD_MOVIE = 'ADD_MOVIE'
export const UPDATE_MOVIE = 'UPDATE_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'
