name: CI
on: [push]
env:
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        cache: 'npm'
    - run: npm install
    - run: npm run build 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 # Change this to the location of your S3 Bucket

    # Change ./_site/ to the location of your website in your repository,
    # with Jekyll _site/ is the default location of the built files
    - name: Deploy to S3 bucket
      run: aws s3 sync build s3://dashboard.ashish.me

    # Remove this step if you're not using CloudFront
    - name: Invalidate CloudFront Objects
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --path "/*"